openapi: 3.0.0
paths:
  /health:
    get:
      operationId: HealthController_check
      parameters: []
      responses:
        "200":
          description: The Health Check is successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  info:
                    type: object
                    example: &a1
                      database: &a2
                        status: up
                    additionalProperties:
                      type: object
                      properties:
                        status:
                          type: string
                      additionalProperties:
                        type: string
                    nullable: true
                  error:
                    type: object
                    example: {}
                    additionalProperties:
                      type: object
                      properties:
                        status:
                          type: string
                      additionalProperties:
                        type: string
                    nullable: true
                  details:
                    type: object
                    example: *a1
                    additionalProperties:
                      type: object
                      properties:
                        status:
                          type: string
                      additionalProperties:
                        type: string
        "503":
          description: The Health Check is not successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  info:
                    type: object
                    example: *a1
                    additionalProperties:
                      type: object
                      properties:
                        status:
                          type: string
                      additionalProperties:
                        type: string
                    nullable: true
                  error:
                    type: object
                    example:
                      redis: &a3
                        status: down
                        message: Could not connect
                    additionalProperties:
                      type: object
                      properties:
                        status:
                          type: string
                      additionalProperties:
                        type: string
                    nullable: true
                  details:
                    type: object
                    example:
                      database: *a2
                      redis: *a3
                    additionalProperties:
                      type: object
                      properties:
                        status:
                          type: string
                      additionalProperties:
                        type: string
  /v1/auth/merchant-signup:
    post:
      operationId: AuthController_merchantSignUp
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MerchantSignupDto"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
      tags:
        - Auth
        - Merchant Sign up
  /v1/auth/merchant-login:
    post:
      operationId: AuthController_merchantLogin
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserAuthDto"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
      tags:
        - Auth
        - Merchant Sign in
  /v1/auth/refresh:
    post:
      operationId: AuthController_refreshTokens
      parameters: []
      responses:
        "200":
          description: ""
      tags:
        - Auth
        - Refresh token
  /v1/merchants:
    get:
      operationId: MerchantController_getMerchant
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
      tags:
        - Merchant
      security:
        - bearer: []
  /v1/projects:
    post:
      operationId: ProjectController_createProject
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProjectDto"
      responses:
        "200":
          description: ""
      tags:
        - Projects
        - Create Project
      security: &a4
        - bearer: []
    get:
      operationId: ProjectController_getProjects
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProjectDto"
      responses:
        "200":
          description: ""
      tags:
        - Projects
        - Get Projects
      security: *a4
  /v1/industries:
    get:
      operationId: IndustryController_getIndustries
      parameters: []
      responses:
        "200":
          description: ""
      tags:
        - Industry
        - Get industries
  /v1/applications:
    post:
      operationId: ApplicationController_createApplication
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProjectDto"
      responses:
        "200":
          description: ""
      tags:
        - Application
        - Create Application
      security: &a5
        - bearer: []
    get:
      operationId: ApplicationController_createProject
      parameters: []
      responses:
        "200":
          description: ""
      tags:
        - Application
        - Get Applications
      security: *a5
info:
  title: Tetrfy
  description: API description
  version: "1.0"
  contact: {}
tags:
  - name: API Modules
    description: ""
servers: []
components:
  schemas:
    MerchantSignupDto:
      type: object
      properties:
        firstName:
          type: string
        middleName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
      required:
        - firstName
        - middleName
        - lastName
        - email
        - password
    UserAuthDto:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    UpsertAddressDto:
      type: object
      properties:
        addressId:
          type: string
        name:
          type: string
        address1:
          type: string
        address2:
          type: string
        city:
          type: string
        region:
          type: string
        country:
          type: string
        phone:
          type: string
        phoneType:
          type: object
      required:
        - name
        - address1
        - address2
        - city
        - region
        - country
        - phone
        - phoneType
    UpsertCompanyDto:
      type: object
      properties:
        companyId:
          type: string
        name:
          type: string
        description:
          type: string
        address:
          $ref: "#/components/schemas/UpsertAddressDto"
      required:
        - name
        - description
        - address
    CreateProjectDto:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        industryId:
          type: string
        company:
          $ref: "#/components/schemas/UpsertCompanyDto"
      required:
        - name
        - description
        - industryId
        - company
